export const GENRE_STARTING_LOCATIONS: Record<string, string[]> = {
  zombie: [
    'Rooftop of an apartment building',
    'Abandoned hospital ward',
    'Fortified police station',
    'Underground subway shelter',
    'Shopping mall barricade',
    'Military checkpoint',
    'School gymnasium turned camp',
    'Countryside farmhouse',
    'City highway overpass',
    'Cargo warehouse by the docks',
  ],
  cultivation: [
    'Outer Sect training grounds',
    'Secluded mountain cave',
    'Spirit stone market town',
    'Clan ancestral hall',
    'Mortal village near the sect',
    'Ancient ruins in the wilderness',
    'Celestial sect main peak',
    'Forbidden forest borderlands',
    'Alchemy pavilion courtyard',
    'Remote mountain hermitage',
  ],
  school: [
    'Homeroom classroom — first day',
    'School rooftop at noon',
    'School gate on opening ceremony',
    'Cafeteria during lunch',
    'After-school clubroom',
    'Library after hours',
    'School festival preparation',
    'Gymnasium during PE class',
    'Science lab after school',
    'Dormitory hallway',
  ],
  cyberpunk: [
    'Neon-lit back alley, Level 3',
    'Corporate megatower lobby',
    'Underground nightclub district',
    'Megacity slums (Sector 7)',
    'Black-market cyber clinic',
    'Hacker den in an old server farm',
    'Sky bridge between towers',
    'Midnight black market',
    'Corporate heist staging area',
    'Refugee shelter in the lower city',
  ],
  fantasy: [
    'Royal capital main square',
    'Village outskirts near a haunted forest',
    'Dungeon entrance — first floor',
    'Mage academy dormitory',
    'Crumbling ancient ruins',
    'Roadside tavern at crossroads',
    'Battlefield outside a walled city',
    'Elven forest border sanctuary',
    'Underground thieves guild hideout',
    'Mountain pass between kingdoms',
  ],
  mafia: [
    'Family office in downtown',
    'Waterfront warehouse at midnight',
    'Private room at a luxury club',
    'Rain-slicked back alley',
    'Casino floor VIP section',
    'Safe house on the east side',
    'Old factory on the outskirts',
    'Restaurant — closed for business',
    'Rooftop of a rival building',
    'Port dock during a shipment',
  ],
  romance: [
    'Coffee shop on a rainy afternoon',
    'University campus courtyard',
    'Train station — missed the last train',
    'Beachside town in summer',
    'Quiet bookstore after closing',
    'Rooftop garden above the city',
    'Home town after years away',
    'Park bench on the first warm day',
    'Hospital corridor — late night',
    'Convenience store at 2 AM',
  ],
  horror: [
    'Old mansion on the hill',
    'Foggy coastal village',
    'Isolated rural hospital',
    'Remote mountain cabin',
    'Underground utility tunnels',
    'Fog-covered forest trail',
    'Abandoned school building',
    'Lakeside resort in off-season',
    'Victorian neighborhood — strange neighbors',
    'Research outpost in the wilderness',
  ],
  detective: [
    'Police precinct — detective floor',
    'Crime scene in a downtown alley',
    'Uptown private detective office',
    'Harbor district at dusk',
    'Late-night all-night diner',
    'City archive basement',
    'Rooftop overlooking the crime district',
    'Underground gambling ring',
    'Embassy district — restricted area',
    'Forensics lab at midnight',
  ],
  space_scifi: [
    'Orbital space station — arrival dock',
    'Frontier colony planet surface',
    'Battlecruiser bridge deck',
    'Asteroid mining rig — shift change',
    'Galaxy gateway hub — customs',
    'Alien megacity underbelly',
    'Scientific research vessel',
    'Abandoned derelict ship',
    'Planet under military occupation',
    'Generation ship — inner colony',
  ],
  military_war: [
    'Forward operating base — dawn briefing',
    'Urban warzone — destroyed city block',
    'Underground command bunker',
    'Border checkpoint under pressure',
    'Field hospital behind the lines',
    'Jungle outpost — deep recon',
    'Coastal amphibious landing zone',
    'Captured enemy supply depot',
    'Mountain sniper position',
    'Evacuation convoy on the highway',
  ],
  apocalypse: [
    'Fortified survivor settlement',
    'Collapsed city ruins — downtown',
    'Highway checkpoint between zones',
    'Underground shelter — day 90',
    'Desolate wasteland road',
    'Abandoned farmstead',
    'Rooftop lookout post',
    'River crossing — contested territory',
    'Old government building turned HQ',
    'Trading outpost at the edge of safety',
  ],
  historical: [
    'Imperial capital — inner court',
    'Border fortress under siege',
    'Mountain village in chaos',
    'Merchant harbor — foreign ships',
    'Royal palace — assassination plot',
    'Ancient temple deep in the hills',
    'Warring battlefield — eve of battle',
    'Remote monastery above the clouds',
    'Warlord banquet — political tension',
    'Capital prison — the night before execution',
  ],
  survival: [
    'Dense forest — lost after a crash',
    'Snowy mountain peak — injured',
    'Desert wasteland — water almost gone',
    'Arctic tundra — supply drop failed',
    'Isolated island after a shipwreck',
    'Underground cave system',
    'River delta — flash flood imminent',
    'Volcanic region — eruption warnings',
    'Abandoned jungle research camp',
    'Flooded coastal lowland',
  ],
  superpower: [
    'Ordinary city street — power awakens',
    'Hero academy — first enrollment day',
    'Underground resistance base',
    'Government research facility',
    'Rooftop hideout above the city',
    'Suburban neighborhood after an incident',
    'Ruined training ground',
    'Detention facility for ability-users',
    'City park — public power incident',
    'Collapsed building rescue operation',
  ],
  isekai: [
    'Fantasy kingdom village square',
    'Dark forest — moments after arrival',
    'City of adventurers — guild hall',
    'Demon territory borderlands',
    'Royal palace — summoned as hero',
    'Ancient ruins in a new world',
    'Port town — ship about to depart',
    'Sky-floating island city',
    'Underground dungeon — first floor',
    'Wasteland far from any civilization',
  ],
  vampire: [
    'Gothic estate — grand dining hall',
    'Underground catacombs — clan gathering',
    'Midnight city — hunting district',
    'Ancient stone castle — arrival',
    'Modern penthouse — bloodline court',
    'Foggy harbor — cargo from the old country',
    'Masquerade ballroom — rival clans',
    'City sewers — fugitive in hiding',
    'Cathedral ruins — ancient feeding ground',
    'Upscale hotel — century-old cover identity',
  ],
  slice_of_life: [
    'Home apartment — lazy morning',
    'Local café — regular table',
    'Neighborhood street — after work',
    'Quiet workplace — late shift',
    'Community park — afternoon',
    'Train station — waiting',
    'Coastal town — family visit',
    'Downtown plaza — people-watching',
    'Convenience store — midnight snack run',
    'Small shared apartment — new roommate arrives',
  ],
  thriller: [
    'International airport — something is wrong',
    'Corporate headquarters — 48th floor',
    'Hotel corridor — wrong room number',
    'Underground parking garage — midnight',
    'Embassy district — under surveillance',
    'Dark highway — car breaks down',
    'Surveillance room — camera shows everything',
    'Harbor warehouse — witness to something wrong',
    'Government building — classified level',
    'Crowded train — target spotted',
  ],
  crime_noir: [
    'Smoky jazz bar — private booth',
    'Rain-soaked back street at 2 AM',
    'Waterfront docks — body found',
    'Private detective office — new client',
    'Underground gambling den',
    'Uptown penthouse — crime scene',
    'Police evidence lockup',
    'Abandoned warehouse — rendezvous gone wrong',
    'Pawn shop front for something darker',
    'Funeral parlor — wrong guest list',
  ],
};
