export const GENRE_SKILL_PATHS: Record<string, string[]> = {
  zombie: ['Mutation Path', 'Hunter Path', 'Hive Path', 'Survivor Path'],
  cultivation: ['Qi Path', 'Body Path', 'Soul Path', 'Dao Path'],
  school: ['Academic Path', 'Social Path', 'Athletic Path', 'Leadership Path'],
  cyberpunk: ['Netrunner Path', 'Combat Path', 'Ghost Path', 'Fixer Path'],
  fantasy: ['Mage Path', 'Knight Path', 'Necromancer Path', 'Summoner Path'],
  mafia: ['Enforcer Path', 'Strategist Path', 'Shadow Path', 'Diplomat Path'],
  romance: ['Bond Path', 'Charisma Path', 'Empathy Path', 'Resolve Path'],
  horror: ['Survivor Path', 'Occultist Path', 'Hunter Path', 'Endurance Path'],
  detective: ['Deduction Path', 'Network Path', 'Shadow Path', 'Evidence Path'],
  space_scifi: ['Pilot Path', 'Engineer Path', 'Soldier Path', 'Explorer Path'],
  military_war: ['Combat Path', 'Command Path', 'Stealth Path', 'Medic Path'],
  apocalypse: ['Survivor Path', 'Leader Path', 'Scavenger Path', 'Warrior Path'],
  historical: ['Noble Path', 'Warrior Path', 'Scholar Path', 'Shadow Path'],
  survival: ['Hunter Path', 'Crafter Path', 'Guide Path', 'Endurance Path'],
  superpower: ['Offense Path', 'Defense Path', 'Support Path', 'Hidden Path'],
  isekai: ['Adventurer Path', 'Magic Path', 'Warrior Path', 'Summoner Path'],
  vampire: ['Blood Path', 'Shadow Path', 'Dominion Path', 'Daywalker Path'],
  slice_of_life: ['Bond Path', 'Growth Path', 'Skill Path', 'Reputation Path'],
  thriller: ['Tactical Path', 'Shadow Path', 'Network Path', 'Survival Path'],
  crime_noir: ['Detective Path', 'Street Path', 'Shadow Path', 'Justice Path'],
};

export const BONUS_CHOICES_BY_GENRE: Record<string, string[]> = {
  zombie: ['Increase Combat', 'Increase Mutation Speed', 'Increase Survival'],
  cultivation: ['Increase Qi Capacity', 'Increase Comprehension', 'Increase Physical Body'],
  school: ['Increase Intelligence', 'Increase Social Influence', 'Increase Athletic Ability'],
  cyberpunk: ['Increase Neural Sync', 'Increase Combat Reflexes', 'Increase Hacking Skill'],
  fantasy: ['Increase Mana', 'Increase Swordsmanship', 'Increase Endurance'],
  mafia: ['Increase Influence', 'Increase Street Cred', 'Increase Negotiation'],
  romance: ['Increase Charisma', 'Increase Empathy', 'Increase Trust'],
  horror: ['Increase Sanity', 'Increase Fear Resistance', 'Increase Perception'],
  detective: ['Increase Deduction', 'Increase Network Contacts', 'Increase Observation'],
  space_scifi: ['Increase Piloting', 'Increase Engineering', 'Increase Combat Training'],
  military_war: ['Increase Tactical Skill', 'Increase Command Authority', 'Increase Endurance'],
  apocalypse: ['Increase Survival', 'Increase Leadership', 'Increase Combat Level'],
  historical: ['Increase Political Influence', 'Increase Combat Mastery', 'Increase Wealth'],
  survival: ['Increase Endurance', 'Increase Foraging', 'Increase Hunting'],
  superpower: ['Increase Power Level', 'Increase Control Mastery', 'Increase Stamina'],
  isekai: ['Increase Magic Proficiency', 'Increase Combat Level', 'Increase Charisma'],
  vampire: ['Increase Blood Rank', 'Increase Dominion', 'Increase Sunlight Resistance'],
  slice_of_life: ['Increase Social Bonds', 'Increase Happiness', 'Increase Skill Mastery'],
  thriller: ['Increase Threat Assessment', 'Increase Deception', 'Increase Intelligence'],
  crime_noir: ['Increase Deduction', 'Increase Street Reputation', 'Increase Contacts'],
};
