export const GENRE_STATS: Record<string, string[]> = {
  zombie:        ['Core Level','Mutation Stability','Infection Evolution','Survival Rank','Biomass Adaptation','Combat Instinct','Scavenging'],
  cultivation:   ['Realm Level','Spiritual Root Purity','Dao Comprehension','Sect Rank','Artifact Proficiency','Qi Density','Mental Fortitude'],
  school:        ['Reputation','Intelligence','Athletic Ability','Social Influence','Club Rank','Academic Score','Leadership'],
  cyberpunk:     ['Neural Sync','Implant Stability','Hacking Skill','Threat Rating','Corporate Influence','Reflex Speed','Black Market Rep'],
  fantasy:       ['Mana Capacity','Swordsmanship','Blessing Rank','Guild Reputation','Elemental Affinity','Magic Control','Endurance'],
  mafia:         ['Influence','Street Cred','Loyalty Rating','Territory Control','Fear Rating','Negotiation','Combat Skill'],
  romance:       ['Trust','Emotional Bond','Relationship Stage','Intimacy Progression','Emotional Stability','Charisma','Empathy'],
  horror:        ['Sanity','Fear Resistance','Survival Instinct','Occult Knowledge','Stealth','Endurance','Perception'],
  detective:     ['Deduction','Evidence Gathering','Network Contacts','Intimidation','Observation','Case Reputation','Legal Knowledge'],
  space_scifi:   ['Neural Interface','Piloting','Engineering Skill','Combat Training','Alien Language','Rank','Exploration Points'],
  military_war:  ['Combat Rank','Tactical Skill','Unit Loyalty','Battlefield Experience','Command Authority','Endurance','Morale'],
  apocalypse:    ['Survival Rank','Group Loyalty','Resource Management','Combat Level','Fortification Skill','Leadership','Endurance'],
  historical:    ['Nobility Rank','Political Influence','Combat Mastery','Court Reputation','Wealth','Loyalty','Strategic Mind'],
  survival:      ['Endurance','Foraging','Crafting','Navigation','Fire Mastery','Hunting','Shelter Building'],
  superpower:    ['Power Level','Control Mastery','Threat Class','Hero Rank','Public Reputation','Combat Score','Stamina'],
  isekai:        ['Adventurer Rank','Magic Proficiency','World Adaptation','Party Reputation','Blessing Level','Combat Level','Charisma'],
  vampire:       ['Blood Rank','Bloodline Purity','Dominion','Age Power','Sunlight Resistance','Influence','Feeding Control'],
  slice_of_life: ['Social Bonds','Life Experience','Happiness','Skill Mastery','Reputation','Relationships','Personal Growth'],
  thriller:      ['Threat Assessment','Survival Instinct','Network Trust','Deception','Combat Readiness','Intelligence','Endurance'],
  crime_noir:    ['Street Reputation','Case Closed Count','Police Heat','Underworld Trust','Combat Skill','Deduction','Contacts'],
};

export const SKILL_FALLBACKS: Record<string, string[]> = {
  zombie:        ["Survivor's Instinct",'Mutation Sense','Blood Trail','Iron Stomach','Scavenger Eye','Dead Silence','Bone Armor'],
  cultivation:   ['Qi Spiral','Iron Body','Dragon Breath','Cloud Step','Dao Eye','Thunder Palm','Void Sense'],
  school:        ['Study Focus','Social Read','Crowd Control','Iron Will','Silent Influence','Quick Study','Pressure Immunity'],
  cyberpunk:     ['Ghost Protocol','Neural Spike','Data Burn','Reflex Boost','System Crack','Chrome Step','Signal Jam'],
  fantasy:       ['Mana Pulse','Blade Aura','Stone Skin','Wind Step','Spirit Sight','Fire Breath','Shadow Cloak'],
  mafia:         ['Street Sense','Iron Nerve','Shadow Deal','Loyalty Oath','Fear Aura','Quick Draw','Network Eyes'],
  romance:       ['Empathy Surge','Trust Shield','Emotional Read','Comfort Aura','Bond Seal','Heart Sense','Calm Presence'],
  horror:        ['Sanity Wall','Fear Feed','Dark Step','Whisper Sense','Void Touch','Pale Aura','Blood Chill'],
  detective:     ['Clue Sight','Logic Chain','Network Tap','Pressure Read','Evidence Lock','Shadow Track','Mind Palace'],
  space_scifi:   ['Reflex Implant','Neural Map','Zero-G Adapt','Shield Sync','Scan Protocol','Void Step','Pulse Strike'],
  military_war:  ['Battle Sense','Iron Discipline','Cover Fire','Tactical Eye','Endurance Wall','Command Voice','Wound Resist'],
  apocalypse:    ['Resource Sense','Group Bond','Fortify','Last Stand','Scavenger','Rally','Threat Read'],
  historical:    ['Noble Bearing','Steel Nerve','Court Sense','Battle Cry','Tactical Mind','Loyalty Bond','Honor Shield'],
  survival:      ['Wild Sense','Endure','Craft Master','Path Find','Fire Soul','Hunt Eye','Shelter Mind'],
  superpower:    ['Power Surge','Control Lock','Threat Sense','Hero Aura','Crowd Read','Speed Burst','Shield Wall'],
  isekai:        ['World Adapt','Magic Eye','Rank Surge','Blessing Touch','Combat Read','Charm Aura','Guide Sense'],
  vampire:       ['Blood Sight','Dominion Wave','Night Step','Thrall Bond','Age Power','Sun Resist','Feed Control'],
  slice_of_life: ['Bond Sense','Life Read','Happiness Aura','Skill Flow','Rep Build','Relation Lock','Growth Eye'],
  thriller:      ['Threat Sense','Survival Lock','Network Read','Deception Aura','Combat Edge','Intel Flow','Endure Wall'],
  crime_noir:    ['Street Eye','Case Lock','Heat Sense','Trust Build','Combat Read','Deduce Flow','Contact Web'],
};
